# dhis2 credentials
dhis2_username: Angelo
dhis2_password: Angelo2019!


# Parametrizacao 
#  ['Kamaxakeni', 'Kampfumu', 'Kamubukwana', 'Kanyaka', 'Katembe', 'Nlhamankulu','Kamavota']
#  Escolha o distrito
distrito: Kamubukwana


#  [ '1_de_junho_cs', 'albasine_cs', 'hulene_psa', 'mavalane_cs', 'mavalane_hg', 'pescadores_ps','romao_psa', '1_de_maio_cs',
#  'polana_canico_cs','1_alto_mae_csurb','hospital_central_de_mapito_hc','hospital_central_pediatrico_de_maputo_hc','malhangalene_cs','maxaquene_csurb',
#  'Hospital_militar_de_maputo','polana_cimento_csurb','porto_csurb','bagamoio_cs','hospital_psiquiatrico_do_infulene_cs','inhagoia_ps',
#  'magoanine_tenda_psa','zimpeto_ps','inhaca_ps','catembe_cs','chamissava_cs','incassane_cs','mutsekwa_ps','centro_de_saude_do_chamanculo_cs',
#  'chamanculo_hg','jose_macamo_cs','jose_macamo_HG','xipamanine_csurb']

# Escolha a US
unidade_sanitaria: magoanine_tenda_psa

# Periodo
# ['Novembro 2020', 'Dezembro 2020','Janeiro 2021','Fevereiro 2021','MarÃ§o 2021','Abril 2021','Maio 2021','Junho 2021','Julho 2021','Agosto 2021','Setembro 2021']

periodo: Janeiro 2021

# Formularios
# ['C&T_Resumo de Cuidados e Tratamento']

formulario: 'C&T_Resumo de Cuidados e Tratamento'

# Location do excell
# default : entro da pasta C:\py-dhis-data-entry\data\ 
excell_location: 'ct_dhis_actualizado.xlsx'

# nome da planilha 
sheet_name: Sheet1


# DHIS url
# default http://mail.ccsaude.org.mz:9090/dhis/
dhis_url: http://mail.ccsaude.org.mz:5459/dhis/


# 
#sobrescrever os dados existentes (Sim/Nao)
# configurar Sim apenas se for para subscrever os dados existentes
override : Sim

##
# directorio do projecto 
#default to C:/py-dhis-data-entry

working_dir: /home/agnaldo/Git/py-dhis-data-entry

# OS windows otr linux
os_type: linux


# Tipo de usuario do DHIS > MEA , admin
# default: MEA
user_role: MEA